name: Python application

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test App
        run: 
          docker-compose run web
          docker-compose exec web python3 manage.py test polls
